
// This file was auto-generated by ML.NET Model Builder. 

using IllnessModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
IllnessModel.ModelInput sampleData = new IllnessModel.ModelInput()
{
    Symptoms = @"cough,mucus production,shortness of breath,chest pain",
    Risk_level = @"low (0.5%",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Disease with predicted Disease from sample data...\n\n");


Console.WriteLine($"Disease: {@"bronchitis"}");
Console.WriteLine($"Symptoms: {@"cough,mucus production,shortness of breath,chest pain"}");
Console.WriteLine($"Risk_level: {@"low (0.5%"}");


var sortedScoresWithLabel = IllnessModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

